---
title: "Quasi-UMIs for Patel 2014 Glioblastoma dataset"
author: "Will Townes"
output: html_document
---

```{r}
suppressPackageStartupMessages(library(SingleCellExperiment))
library(tidyverse); theme_set(theme_bw())
library(glmpca)
source("./algs/quminorm.R") #also loads nblomax.R,poilog.R
source("./algs/existing.R") #pca and umap wrapper functions
fp<-file.path
bp<-"./real/patel_2014"

plt_dir<-fp(bp,"results/plots/qumi")
if(!dir.exists(plt_dir)){ dir.create(plt_dir,recursive=TRUE) }
```

## Apply normalizations

```{r}
sce0<-readRDS(fp(bp,"data/02_sce_all_genes_filtered_cells.rds"))
#exclude bulk RNA-seq samples
cm<-colData(sce0)
cc<-cm$sampleType=="SC"
sce<-sce0[,cc]
cm<-as.data.frame(cm[cc,])
m<-assay(sce,"tpm")
gg<-Matrix::rowSums(m)>0
sce<-sce[gg,]
m<-m[gg,]

#create covariate for batch
batch<-as.character(cm$sample)
batch[batch=="MGH26" & cm$instrument=="GLPB22-B5C"]<-"MGH26a"
batch[batch=="MGH26" & cm$instrument=="HISEQ"]<-"MGH26b"
cm$batch<-factor(batch)
cm$subType<-factor(cm$subType) #remove "" level
colData(sce)<-DataFrame(cm)

#compute scran counts with pre-clustering
cl<-scran::quickCluster(sce)
sce<-scran::computeSumFactors(sce,clusters=cl)
sce<-scater::logNormCounts(sce,log=FALSE) #normcounts assay
#compute census counts, 95sec
system.time(sce<-census_normalize(sce,assay_name="tpm"))
#quantile normalize to QUMIs (Poisson-lognormal), 111sec
system.time(qm<-quminorm_matrix(m,shape=2.0,lik="poilog"))
assay(sce,"qumi_poilog")<-qm
#quantile normalize to Poisson-Lomax, 608 sec
#system.time(qm<-quminorm_matrix(m,shape=1.0,lik="plomax"))
#assay(sce,"qumi_plomax")<-qm
saveRDS(sce,file=fp(bp,"data/03_sce_filtered_cells_quminorm.rds"))
```

## Visualize effect of normalizations

Show normalizations don't align the two batches of MGH26.

```{r}
#sce<-readRDS(fp(bp,"data/03_sce_filtered_cells_quminorm.rds"))
cm<-colData(sce)
ss<-sce[,cm$sample=="MGH26"]
cm_ss<-colData(ss)
cm_ss$batch<-factor(cm_ss$batch)
sp<-split(rownames(cm_ss),cm_ss$batch)
ncell<-20 #20 random cells from each batch
cells<-unlist(lapply(sp,sample,ncell))
res<-list()
for(m in c("counts","tpm","census_counts","qumi_poilog")){
  X<-assay(ss,m)
  f<-function(i){
    x<-X[,i]
    data.frame(x=log10(x[x>0]),mth=m,cell=i,batch=cm_ss[i,"batch"])
  }
  res[[m]]<-do.call(rbind,lapply(cells,f))
}
pd<-do.call(rbind,res)
levels(pd$mth)[levels(pd$mth)=="counts"] <- "read_counts"

pd2<-subset(pd,mth!="qumi_poilog")
ggplot(pd2,aes(x=x,group=cell,color=batch,alpha=batch))+geom_line(stat="density")+facet_wrap(~mth,scales="free",nrow=1)+xlab("log10(expression)")+scale_alpha_manual(values=c(1,.5))+theme(legend.position = "none")
ggsave(fp(plt_dir,"normalize_patel_distr.pdf"),width=8,height=3)

#split plots into separate files for latex
ggplot(subset(pd2,mth=="read_counts"),aes(x=x,group=cell,color=batch,alpha=batch))+geom_line(stat="density")+xlab("log10(expression)")+scale_alpha_manual(values=c(1,.5))+theme(legend.position = "none")
ggsave(fp(plt_dir,"normalize_patel_distr_rc.pdf"),width=3,height=3)

ggplot(subset(pd2,mth=="tpm"),aes(x=x,group=cell,color=batch,alpha=batch))+geom_line(stat="density")+xlab("log10(expression)")+scale_alpha_manual(values=c(1,.5))+theme(legend.position = "none",axis.title.y=element_blank())
ggsave(fp(plt_dir,"normalize_patel_distr_tpm.pdf"),width=3,height=3)

ggplot(subset(pd2,mth=="census_counts"),aes(x=x,group=cell,color=batch,alpha=batch))+geom_line(stat="density")+xlab("log10(expression)")+scale_alpha_manual(values=c(1,.5))+theme(legend.position = "none",axis.title.y=element_blank())
ggsave(fp(plt_dir,"normalize_patel_distr_census.pdf"),width=3,height=3)
```

## Dimension reduction

We will examine the effects of four normalizations on dimension reduction: TPM, scran, census, and QUMIs. We will use PCA, UMAP, and GLM-PCA for dimension reduction. 

```{r}
sce<-readRDS(fp(bp,"data/03_sce_filtered_cells_quminorm.rds"))
gg<-scan(file=fp(bp,"extdata/genes_patel_used.txt"),what="character")
assayNames(sce)[assayNames(sce)=="normcounts"]<-"scran"
anames<-setdiff(assayNames(sce),"counts")
#subset only tumor MGH26
#sce<-sce[,colData(sce)$tumorName=="MGH26"]

f<-function(a,L,drfunc=c("pca","umap","tsne","glmpca")){
  #a is an assay name from sce
  message(a)
  drfunc<-match.arg(drfunc)
  m<-assay(sce,a)
  res<-as.data.frame(colData(sce)[,c("batch","subType","instrument")])
  res$normalization<-a
  res$zero_frac<-colMeans(m>0)
  res$cell<-rownames(res); rownames(res)<-NULL
  if(drfunc=="pca"){
    dimreduce_func<-function(m){pca(m,L=L,rmzero=TRUE,scale=TRUE)}
  } else if(drfunc=="umap"){
    dimreduce_func<-function(m){umap(as.matrix(m),L=L)}
  } else if(drfunc=="tsne"){
    dimreduce_func<-function(m){tsne(as.matrix(m),L=L)}
  } else if(drfunc=="glmpca"){
    m<-m[gg,]
    m<-m[rowSums(m)>0,]
    factors<-glmpca(m,L,fam="nb",penalty=1)$factors
    return(cbind(res,factors))
  } else { 
    stop("invalid dimension reduction") 
  }
  #if(a %in% c("census_counts","qumi_poilog")){
    cs<-colSums(m)
    m<-t(t(m)/cs)*median(cs)
  #}
  #m<-t(t(m)/colSums(m))
  m<-m[gg,]
  m<-m[rowSums(m)>0,]
  #m<-log2(1+m[rowSums(m)>0,])
  cbind(res,dimreduce_func(m))
}
pca_pd<-do.call(rbind,lapply(anames,f,L=2,drfunc="pca"))
pca_pd$dimreduce<-"pca"
ggplot(pca_pd,aes(x=dim1,y=dim2,colour=batch))+geom_point()+facet_wrap(~normalization,scales="free")
ggplot(subset(pca_pd,batch %in% c("MGH26a","MGH26b")),aes(x=dim1,y=dim2,colour=batch))+geom_point()+facet_wrap(~normalization,scales="free")

umap_pd<-do.call(rbind,lapply(anames,f,L=2,drfunc="umap"))
umap_pd$dimreduce<-"umap"
ggplot(umap_pd,aes(x=dim1,y=dim2,colour=batch))+geom_point()+facet_wrap(~normalization,scales="free")

tsne_pd<-do.call(rbind,lapply(anames,f,L=2,drfunc="tsne"))
tsne_pd$dimreduce<-"tsne"
ggplot(tsne_pd,aes(x=dim1,y=dim2,colour=batch))+geom_point()+facet_wrap(~normalization,scales="free")

set.seed(222)
glmpca_pd<-do.call(rbind,lapply(c("qumi_poilog","census_counts"),f,L=2,drfunc="glmpca"))
glmpca_pd$dimreduce<-"glmpca"
ggplot(glmpca_pd,aes(x=dim1,y=dim2,colour=batch))+geom_point()+facet_wrap(~normalization,scales="free")
ggplot(subset(glmpca_pd,batch %in% c("MGH26a","MGH26b")),aes(x=dim1,y=dim2,colour=batch))+geom_point()+facet_wrap(~normalization,scales="free")

pd<-rbind(pca_pd,tsne_pd,glmpca_pd)
pd$normalization<-plyr::mapvalues(pd$normalization,from=c("census_counts","qumi_poilog"),to=c("census","qumi"))
pd$method<-paste0(pd$normalization,"_",pd$dimreduce)
colnames(pd)[colnames(pd)=="batch"]<-"tumor"
write.table(pd,fp(bp,"results/qumi_glmpca_patel.txt"),quote=FALSE,row.names=FALSE)
```

```{r}
pd<-read.table(fp(bp,"results/qumi_glmpca_patel.txt"),header=TRUE)
pd2<-subset(pd,dimreduce!="tsne")
pd2$method<-factor(as.character(pd2$method),levels=c("tpm_pca","scran_pca","census_pca","qumi_pca","census_glmpca","qumi_glmpca"))
ggplot(pd2,aes(x=dim1,y=dim2,colour=tumor))+geom_point(size=.7,alpha=.9)+facet_wrap(~method,scales="free",nrow=3)+xlab("dimension 1")+ylab("dimension 2")#+theme(legend.position = "bottom")
ggsave(file=fp(plt_dir,"qumi_dimreduce_patel1.pdf"),width=5,height=6)

#ggplot(pd2,aes(x=zero_frac,y=dim1,colour=tumor))+geom_point()+facet_wrap(~method,scales="free",nrow=3)+xlab("zero fraction")+ylab("dimension 1")#+theme(legend.position = "bottom")
#ggsave(file=fp(plt_dir,"qumi_dimreduce_patel2.pdf"),width=5,height=6)

pd3<-subset(pd,dimreduce=="tsne")
ggplot(pd3,aes(x=dim1,y=dim2,colour=tumor))+geom_point()+facet_wrap(~normalization,scales="free")+xlab("dimension 1")+ylab("dimension 2")
ggsave(file=fp(plt_dir,"qumi_tsne_patel.pdf"),width=5,height=3)

#pd2 %>% group_by(method) %>% summarize(pzcor=cor(zero_frac,dim1)) %>% arrange(abs(pzcor))
```
