---
title: "QUMIs"
author: "Will Townes"
date: "4/15/2019"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2); theme_set(theme_bw())
library(ggridges)
fp<-file.path
plt_dir<-fp("./qumi/results/fig")
if(!dir.exists(plt_dir)){ dir.create(plt_dir,recursive=TRUE) }
```

load MLEs and BIC values for the three training datasets for all three models.

```{r}
klein_celltypes<-SingleCellExperiment::colData(readRDS("./real/klein_2015/data/01_sce_all_genes_all_cells.rds"))$cell_type1
klein_groups<-as.character(klein_celltypes)
klein_groups[klein_groups %in% c("d0","d7")]<-"d0d7"
klein_groups[klein_groups %in% c("d2","d4")]<-"d2d4"
dats<-c("cao_2017","klein_2015","zeisel_2015")
mods<-c("nb","poilog","poilomax")
res<-list()
for(m in mods){
  res[[m]]<-list()
  for(d in dats){
    df<-read.table(fp("./real",d,"data",paste0("mle_",m,".txt")),header=TRUE)
    df$dataset<-if(d=="klein_2015"){ paste(d,klein_groups,sep="_") } else { d }
    df$model<-m
    df$cell_id<-rownames(df)
    res[[m]][[d]]<-df
  }
  res[[m]]<-do.call(rbind,res[[m]])
  res[[m]]$dataset<-factor(res[[m]]$dataset,levels=sort(unique(res[[m]]$dataset),decreasing=TRUE))
  rownames(res[[m]])<-NULL
}
#extract BIC and log likelihoods
bic_df<-lapply(res,function(x){x[,c("dataset","cell_id","model","loglik","bic")]})
bic_df<-do.call(rbind,bic_df)
rownames(bic_df)<-NULL
#extract MLEs
res2<-res
res2[["nb"]]<-res[["nb"]][,c("dataset","cell_id","model","size")]
res2[["poilog"]]<-res[["poilog"]][,c("dataset","cell_id","model","sig")]
res2[["poilomax"]]<-res[["poilomax"]][,c("dataset","cell_id","model","tail")]
#for(m in mods){
#  colnames(res2[[m]])[4]<-"shape"
#}
#mle_df<-do.call(rbind,res2)
#rownames(mle_df)<-NULL
```

Make plots of MLEs

```{r}
ggplot(res2[["nb"]],aes(x=size,y=dataset,fill=dataset))+geom_density_ridges(scale=1.8,alpha=.9,rel_min_height=.0001)+theme(legend.position="none")+xlab("shape")+scale_x_log10()
ggsave(fp(plt_dir,"nb_mles.pdf"),width=3,height=2.7)

ggplot(res2[["poilog"]],aes(x=sig,y=dataset,fill=dataset))+geom_density_ridges(scale=1.8,alpha=.9,rel_min_height=.0001)+theme(legend.position="none")+xlab("shape")+ylab(NULL)+scale_x_log10()
ggsave(fp(plt_dir,"poilog_mles.pdf"),width=3,height=2.7)
ggsave(fp(plt_dir,"poilog_mles_big.pdf"),width=6,height=4)

ggplot(res2[["poilomax"]],aes(x=tail,y=dataset,fill=dataset))+geom_density_ridges(scale=1.8,alpha=.9,rel_min_height=.0001)+theme(legend.position="none")+scale_x_log10(limits=c(min(res2[["poilomax"]]$tail),10))+xlab("shape")+ylab(NULL)
ggsave(fp(plt_dir,"poilomax_mles.pdf"),width=3,height=2.7)
```

Make plots of BIC

```{r}
bic_df$dataset<-as.character(bic_df$dataset)
bic_df$dataset[grep("klein_2015",bic_df$dataset)]<-"klein_2015"
ggplot(bic_df,aes(x=model,fill=model,y=-loglik))+geom_boxplot()+facet_wrap(~dataset,scales="free")+scale_y_log10()+theme(axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank())+ylab("negative log likelihood")
ggsave(fp(plt_dir,"loglik_boxplot.pdf"),width=6,height=4)
```

Load distance scores

```{r}
dats<-c("macosko_2015","tung_2016","zheng_2017_monocytes")
res<-list()
for(d in dats){
  res[[d]]<-read.table(fp("./real",d,"results/qumi_distance.txt"),header=TRUE)
  res[[d]]$dataset<-d
}
res<-do.call(rbind,res)
rownames(res)<-NULL

pd<-gather(res,key="method",value="distance",-c(dataset,cell))
pd<-subset(pd,method!="counts")
pd2<-pd %>% group_by(method) %>% summarize(med_dist=median(distance,na.rm=TRUE))
o<-order(pd2$med_dist,decreasing=FALSE)
pd$method<-factor(pd$method,levels=pd2$method[o])
#pd3<-subset(pd,!(method %in% c("scran_counts","cpm")))
pd3<-subset(pd,method %in% c("read_counts","census_counts","qumi_poilog","qumi_poilog1"))
pd3$method<-plyr::mapvalues(pd3$method,from=c("read_counts","census_counts","qumi_poilog","qumi_poilog1"),to=c("reads","census","qumi2","qumi1"))
ggplot(pd3,aes(x=method,y=distance,fill=method,colour=method))+geom_boxplot()+scale_y_log10()+ylab("distance from UMI counts")+facet_wrap(~dataset,nrow=1,scales="free")+theme(legend.position="none")#+theme(axis.text.x = element_text(angle = 15, hjust=1)) #+coord_flip()
ggsave(fp(plt_dir,"dist_comp.pdf"),width=7,height=3)
```
